### ISSUE TITLE
Implement an application: Starship belly-flop manoeuvre

### ISSUE THREAD

**Issue by JinraeKim** [JinraeKim/ContinuousTimePolicyGradients.jl#4]
Advisor: @nhcho91

**Comment by nhcho91** [comment]
We may refer to the following paper for the problem data and formulation:
https://elib.dlr.de/143015/1/Sagliano_2021f.pdf

There is also another repo with the starship-like dynamics implemented:
https://github.com/dmalyuta/scp_traj_opt

Note:
Besides the rocket landing problem, Mars atmosphere entry guidance can be another interesting application.
http://dx.doi.org/10.2514/1.G002818
